version: '3.1'

services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      restart: always
      ports:
      - 8091:80
      volumes:
      - /sessions